baseURL = 'https://dev.lkarrie.com'
defaultContentLanguage = 'zh-CN'
title = 'LKarrie'
enableEmoji = true
[outputs]
  home = [ "HTML", "RSS"]

[languages]
  [languages.zh-CN]
    contentDir = 'content/zh-CN'
    languageCode = 'zh-CN'
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en'

[Params]
  description = 'é›‘é­šã®å°ç«™'
  defaulBanner = '/img/silverwolf.jpg'
  defaulLazyBanner ='/imglazy/silverwolf-lazy.jpg'
  defaulCardImg = '/img/weighanchor1.png'
  defaulLazyCardImg ='/imglazy/weighanchor1-lazy.png'
  syntaxHighlighter = "highlight.js"
  helloText = 'Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello! ^^ .'
  newFeatureTitle = 'New feature!'
  newFeatureImg = '/img/silverwolf.jpg'
  newFeatureDes = 'new new new feature!'

[Params.weighanchor.one.en]
  title = 'one'
  image = '/img/weighanchor1.png'
  description = 'weighanchor one'
  url = '/about'
  
[Params.weighanchor.two.en]
  title = 'two'
  image = '/img/weighanchor1.png'
  description = 'weighanchor two'
  url = '/'

[Params.weighanchor.three.en]
  title = 'three'
  image = '/img/weighanchor1.png'
  description = 'weighanchor three'
  url = '/'

[Params.weighanchor.one.zhCN]
  title = 'one zhCN'
  image = '/img/weighanchor1.png'
  description = 'weighanchor one zhCN'
  url = '/'

[Params.weighanchor.two.zhCN]
  title = 'two zhCN'
  image = '/img/weighanchor1.png'
  description = 'weighanchor two zhCN'
  url = '/'

[Params.weighanchor.three.zhCN]
  title = 'three zhCN'
  image = '/img/weighanchor1.png'
  description = 'weighanchor three zhCN'
  url = '/'

[Params.mobile]
  avatar = '/img/avatar.jpg'
  helloText = 'hello this is my mobile version'

[Params.newFeature.en]
  title = 'New feature!'
  image = '/img/silverwolf.jpg'
  description = 'new new new feature!'
  url = '/'

[Params.newFeature.zhCN]
  title = 'æ²¡ç”¨çš„åŠŸèƒ½åˆå¢åŠ äº†ğŸ§'
  image = '/img/silverwolf.jpg'
  description = '1.æ–°å¢é»‘ç™½æ¨¡å¼;2.æ–°å¢ä¸­è‹±æ–‡ç¿»è¯‘... è¯¦ç»†ä¿¡æ¯æˆ³æˆ‘ä¸€ä¸‹'
  url = '/'

[Params.mobile.description.en]
  menuDes = 'Where u wanna go ? ~'

[Params.mobile.description.zhCN]
  menuDes = 'ä½ æƒ³å»å“ª ? ~ ğŸ¤”'  

[Params.archive.description.en]
  default = 'blog archive'

[Params.archive.description.zhCN]
  default = 'æ–‡ç« å½’æ¡£'

[Params.tags.description.en]
  default = 'blog tags'  
  minecraft = 'mc mc mc !'

[Params.tags.description.zhCN]
  default = 'æ–‡ç« æ ‡ç­¾'  
  minecraft = 'mc mc mc ~'

[Params.categories.description.en]
  default = 'blog categories'
  game = 'happy game time~ ğŸ®'

[Params.categories.description.zhCN]
  default = 'æ–‡ç« åˆ†ç±»'
  game = 'æ¸¸æˆ~ ğŸ®'

[Params.home]
  showVideo = false
  homeBgStartIndex = 0
  homeBgEndIndex = 1
  homeBgImage = '/img/home'
  homeBgImageSuffix = 'jpg'
  homeBgVideo = 'https://dev.lkarrie.com/media/silverwolf.mp4/index.m3u8'
  github = 'https://github.com/LKarrie'
  mail = 'lkarrie@163.com'
  wechat = 'https://dev.lkarrie.com/wechat'
  qq = '3024505225'
  weibo = 'https://weibo.com/u/6707437821'
  steam = 'https://steamcommunity.com/id/LKarrie'


[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6