baseURL = 'https://dev.lkarrie.com'
languageCode = 'zh-cn'
title = 'LKarrie'
paginate = '1'
enableEmoji = true
[outputs]
    home = [ "HTML", "RSS"]

[Params]
  description = '雑魚の小站'
  defaulBanner = '/img/silverwolf.jpg'
  defaulLazyBanner ='/imglazy/silverwolf-lazy.jpg'
  defaulCardImg = '/img/weighanchor1.png'
  defaulLazyCardImg ='/imglazy/weighanchor1-lazy.png'
  syntaxHighlighter = "highlight.js"
  helloText = 'Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello! ^^ .'
  newFeatureTitle = 'New feature!'
  newFeatureImg = '/img/silverwolf.jpg'
  newFeatureDes = 'new new new feature!'

[Params.mobile]
  avatar = '/img/avatar.jpg'
  helloText = 'hello this is my mobile version'
  menuTitle = 'Menu'
  menuDes = 'Where u wanna go ?~'

[Params.categories.description]
  game = 'happy game time~'
  default = 'categories.description'

[Params.archive.description]
  default = 'archive.description'

[Params.tags.description]
  minecraft = 'mc mc mc'
  default = 'tags.description'  

[Params.home]
  showVideo = false
  homeBgStartIndex = 0
  homeBgEndIndex = 1
  homeBgImage = '/img/home'
  homeBgImageSuffix = 'jpg'
  homeBgVideo = 'https://dev.lkarrie.com/media/silverwolf.mp4/index.m3u8'
  github = 'https://github.com/LKarrie'
  mail = 'lkarrie@163.com'
  wechat = 'https://dev.lkarrie.com/wechat'
  qq = '3024505225'
  weibo = 'https://weibo.com/u/6707437821'
  steam = 'https://steamcommunity.com/id/LKarrie'


[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6