baseURL = 'https://blog.lkarrie.com'
defaultContentLanguage = 'zh-CN'
title = 'LKarrie'
enableEmoji = true
[outputs]
  home = [ "HTML", "RSS"]

[languages]
  [languages.zh-CN]
    contentDir = 'content/zh-CN'
    languageCode = 'zh-CN'
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en'

[Params]
  description = 'é›‘é­šã®å°ç«™'
  defaulBanner = '/img/silverwolf.jpg'
  defaulLazyBanner ='/imglazy/silverwolf-lazy.jpg'
  defaulCardImg = '/img/weighanchor1.png'
  defaulLazyCardImg ='/imglazy/weighanchor1-lazy.png'
  syntaxHighlighter = "highlight.js"
  helloText = 'âš¡peace~ peace~ peace~ peace~ peace~ âš¡'
  newFeatureTitle = 'New feature!'
  newFeatureImg = '/img/silverwolf.jpg'
  newFeatureDes = 'new new new feature!'
  disableWeighanchorLoadAnime = true
  disableDiscoveryLoadAnime = true
  fancybox = true

[Params.views.plausible]
  enable = true
  url = 'analytics.lkarrie.com'
  site = 'blog.lkarrie.com'

[Params.weighanchor.one.en]
  title = 'Under Maintenance'
  image = '/img/weighanchor1.jpg'
  description = 'Oops sry :('
  url = '/'
  
[Params.weighanchor.two.en]
  title = 'Under Maintenance'
  image = '/img/weighanchor2.jpg'
  description = 'Oops sry :('
  url = '/'

[Params.weighanchor.three.en]
  title = 'Under Maintenance'
  image = '/img/weighanchor3.jpg'
  description = 'ç»´æŠ¤ä¸­... ä¸‹æ¬¡å†æ¥çœ‹çœ‹å§:)'
  url = '/'

[Params.weighanchor.one.zhCN]
  title = 'ç»´æŠ¤ä¸­...'
  image = '/img/weighanchor1.jpg'
  description = 'ç»´æŠ¤ä¸­... ä¸‹æ¬¡å†æ¥çœ‹çœ‹å§:)'
  url = '/'

[Params.weighanchor.two.zhCN]
  title = 'ç»´æŠ¤ä¸­...'
  image = '/img/weighanchor2.jpg'
  description = 'ç»´æŠ¤ä¸­... ä¸‹æ¬¡å†æ¥çœ‹çœ‹å§:)'
  url = '/'

[Params.weighanchor.three.zhCN]
  title = 'ç»´æŠ¤ä¸­...'
  image = '/img/weighanchor3.jpg'
  description = 'ç»´æŠ¤ä¸­... ä¸‹æ¬¡å†æ¥çœ‹çœ‹å§:)'
  url = '/'

[Params.mobile]
  avatar = '/img/avatar.jpg'
  helloText = 'hello this is my mobile version'

[Params.newFeature.en]
  title = 'New feature!'
  image = '/img/silverwolf.jpg'
  description = 'new new new feature!'
  url = '/'

[Params.newFeature.zhCN]
  title = 'æ²¡ç”¨çš„åŠŸèƒ½åˆå¢åŠ äº†ğŸ§'
  image = '/img/silverwolf.jpg'
  description = '1.æ–°å¢é»‘ç™½æ¨¡å¼;2.æ–°å¢ä¸­è‹±æ–‡ç¿»è¯‘... è¯¦ç»†ä¿¡æ¯æˆ³æˆ‘ä¸€ä¸‹'
  url = '/'

[Params.mobile.description.en]
  menuDes = 'Where u wanna go ? ~'

[Params.mobile.description.zhCN]
  menuDes = 'ä½ æƒ³å»å“ª ? ~ ğŸ¤”'  

[Params.archive.description.en]
  default = 'blog archive'

[Params.archive.description.zhCN]
  default = 'æ–‡ç« å½’æ¡£'

[Params.tags.description.en]
  default = 'blog tags'  
  minecraft = 'mc mc mc !'

[Params.tags.description.zhCN]
  default = 'æ–‡ç« æ ‡ç­¾'  
  minecraft = 'mc mc mc ~'

[Params.categories.description.en]
  default = 'blog categories'
  game = 'happy game time~ ğŸ®'

[Params.categories.description.zhCN]
  default = 'æ–‡ç« åˆ†ç±»'
  game = 'æ¸¸æˆ~ ğŸ®'

[Params.links.description.en]
  default = 'friend link'

[Params.links.description.zhCN]
  default = 'å°ä¼™ä¼´ä»¬~'

[Params.home]
  showVideo = false
  homeBgStartIndex = 0
  homeBgEndIndex = 1
  homeBgImage = '/img/home'
  homeBgImageSuffix = 'jpg'
  homeBgVideo = 'https://blog.lkarrie.com/media/silverwolf.mp4/index.m3u8'
  github = 'https://github.com/LKarrie'
  mail = 'lkarrie@163.com'
  wechat = 'https://blog.lkarrie.com/wechat'
  qq = '3024505225'
  weibo = 'https://weibo.com/u/6707437821'
  steam = 'https://steamcommunity.com/id/LKarrie'

[[Params.link]] 
  name = 'HAHA'
  url = 'https://deployment.net.cn/'
  logo = 'https://image.lkarrie.com/images/2022/02/12/HAHA.jpg'
[[Params.link]] 
  name = 'ä¸äºˆã®æµ‹è¯•ç¬”è®°'
  url = 'https://www.shibuyu.fun'
  logo = 'https://www.shibuyu.fun/logo'
[[Params.link]] 
  name = 'å–µé›¨ã®å°å±‹'
  url = 'https://meowrain.cn'
  logo = 'https://meowrain.cn/upload/2022/06/Snipaste_2022-06-30_20-24-55.png'    
[[Params.link]] 
  name = 'ä½è°ƒå°ç†ŠçŒ«'
  url = 'https://ilovey.live'
  logo = 'https://uss.ilovey.live/img/avatar.jpg'    
[[Params.link]] 
  name = 'å®‡ç”Ÿã®åèŠ±å›­'
  url = 'https://blog.yuse.cc'
  logo = 'https://pan.yuse.cc/d/imgu/avatar.jpg'    
[[Params.link]] 
  name = 'å¢¨è¨€ç¬™æ­Œ'
  url = 'https://gxjblog.com'
  logo = 'https://images-1313401033.cos.ap-beijing.myqcloud.com/accessory/headPortrait.jpeg'    
[[Params.link]] 
  name = 'å‡›éŸ³çš„å¥‡å¹»æ ‘å±‹'
  url = 'https://www.rinne.ink'
  logo = 'https://public-1306037490.cos.ap-beijing.myqcloud.com/logo.jpg'     
[[Params.link]] 
  name = 'FGHRSH'
  url = 'https://www.fghrsh.net'
  logo = '//fp1.fghrsh.net/2017/10/11/d383a9ad4318c5b4332fe02845f5323a.jpg'    
[[Params.link]] 
  name = 'Takagi'
  url = 'https://lixingyong.com/'
  logo = 'https://image.lkarrie.com/images/2022/07/03/takagi.webp'        
[[Params.link]] 
  name = 'Mashiro'
  url = 'https://2heng.xin/'
  logo = 'https://image.lkarrie.com/images/2022/07/03/mashiro.jpg'

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6